# -*- coding: utf-8 -*-
"""yolov8m.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TUdksijzywv-md_Sv-4YrLJpxGLeUFzh
"""

!nvidia-smi

import os
HOME = os.getcwd()
print(HOME)

from google.colab import drive
drive.mount('/content/drive')

!pip install ultralytics

import ultralytics

import glob
from IPython.display import Image, display

ultralytics.checks()

from ultralytics import YOLO

!ls  '/content/drive/MyDrive/Data298AandB/Grounding_DINO/YOLO_Classification/data'

#import shutil
#shutil.rmtree('/content/drive/MyDrive/Data298AandB/Grounding_DINO/YOLO_Classification/data/runs', ignore_errors=True)

#!ls  '/content/drive/MyDrive/Data298AandB/Grounding_DINO/YOLO_Classification/data'

#Already unzipped
#!unzip -u '/content/gdrive/MyDrive/Data298AandB/data/train_val_test.zip' -d '/content/gdrive/MyDrive/Data298AandB/data'

DATA_DIR= '/content/drive/MyDrive/Data298AandB/Grounding_DINO/YOLO_Classification/data'
DATA_DIR

!ls '/content/drive/MyDrive/Data298AandB/Grounding_DINO/YOLO_Classification/data'

DATA_DIR

os.getcwd()

os.chdir('/content/drive/MyDrive/Data298AandB/Grounding_DINO/YOLO_Classification/data')
os.getcwd()

#!yolo task=classify mode=train model=yolov8m-cls.pt data='{DATA_DIR}' epochs=10 imgsz=416
!yolo task=classify mode=train data='{DATA_DIR}' model=yolov8m-cls.pt epochs=100 imgsz=640

{HOME}

!ls  '/content/drive/MyDrive/Data298AandB/data/train_val_test/runs/classify/train'

!ls  '/content/drive/MyDrive/Data298AandB/data/train_val_test/runs/classify/train/weights'

{DATA_DIR}

!yolo task=classify mode=val data='{DATA_DIR}' model={HOME}/drive/MyDrive/Data298AandB/data/train_val_test/runs/classify/train/weights/best.pt

Image(filename=f'{HOME}/drive/MyDrive/Data298AandB/data/train_val_test/runs/classify/val2/confusion_matrix.png')

Image(filename=f'{HOME}/drive/MyDrive/Data298AandB/data/train_val_test/runs/classify/val2/confusion_matrix_normalized.png')

Image(filename=f'{HOME}/drive/MyDrive/Data298AandB/data/train_val_test/runs/classify/train/results.png')

Image(filename=f'{HOME}/drive/MyDrive/Data298AandB/data/train_val_test/runs/classify/train/train_batch0.jpg')

Image(filename=f'{HOME}/drive/MyDrive/Data298AandB/data/train_val_test/runs/classify/train/train_batch1.jpg')

Image(filename=f'{HOME}/drive/MyDrive/Data298AandB/data/train_val_test/runs/classify/train/train_batch2.jpg')

Image(filename=f'{HOME}/drive/MyDrive/Data298AandB/data/train_val_test/runs/classify/train/val_batch0_labels.jpg')

Image(filename=f'{HOME}/drive/MyDrive/Data298AandB/data/train_val_test/runs/classify/train/val_batch0_pred.jpg')

Image(filename=f'{HOME}/drive/MyDrive/Data298AandB/data/train_val_test/runs/classify/val2/val_batch2_labels.jpg')

Image(filename=f'{HOME}/drive/MyDrive/Data298AandB/data/train_val_test/runs/classify/val2/val_batch2_pred.jpg')

# Commented out IPython magic to ensure Python compatibility.
# %cd {HOME}
!yolo task=classify mode=predict model={HOME}/drive/MyDrive/Data298AandB/data/train_val_test/runs/classify/train/weights/best.pt conf=0.25 source='{HOME}/drive/MyDrive/Data298AandB/data/train_val_test/test/furniture'

!ls '{HOME}/runs/classify/predict'

#from ultralytics.models.rtdetr import predict
import glob
from IPython.display import Image,display

for image_path in glob.glob(f'{HOME}/runs/classify/predict/*.jpg')[:10]:
  print(image_path)
  display(Image(filename=image_path, height = 416))
  print('\n')

# Commented out IPython magic to ensure Python compatibility.
# %cd {HOME}
!yolo task=classify mode=predict model={HOME}/drive/MyDrive/Data298AandB/data/train_val_test/runs/classify/train/weights/best.pt conf=0.25 source='{HOME}/drive/MyDrive/Data298AandB/data/train_val_test/test/plastic'

#from ultralytics.models.rtdetr import predict
import glob
from IPython.display import Image,display

for image_path in glob.glob(f'{HOME}/runs/classify/predict2/*.jpg')[:10]:
  print(image_path)
  display(Image(filename=image_path, height = 416))
  print('\n')

!yolo task=classify mode=predict model={HOME}/drive/MyDrive/Data298AandB/data/train_val_test/runs/classify/train/weights/best.pt conf=0.25 source='{HOME}/drive/MyDrive/Data298AandB/data/train_val_test/test/biowaste'

#from ultralytics.models.rtdetr import predict
import glob
from IPython.display import Image,display

for image_path in glob.glob(f'{HOME}/runs/classify/predict3/*.jpg')[:10]:
  print(image_path)
  display(Image(filename=image_path, height = 416))
  print('\n')

!yolo task=classify mode=predict model={HOME}/drive/MyDrive/Data298AandB/data/train_val_test/runs/classify/train/weights/best.pt conf=0.25 source='{HOME}/drive/MyDrive/Data298AandB/data/train_val_test/test/glass'

#from ultralytics.models.rtdetr import predict
import glob
from IPython.display import Image,display

for image_path in glob.glob(f'{HOME}/runs/classify/predict4/*.jpg')[:10]:
  print(image_path)
  display(Image(filename=image_path, height = 416))
  print('\n')

!yolo task=classify mode=predict model={HOME}/drive/MyDrive/Data298AandB/data/train_val_test/runs/classify/train/weights/best.pt conf=0.25 source='{HOME}/drive/MyDrive/Data298AandB/data/train_val_test/test/clothes'

for image_path in glob.glob(f'{HOME}/runs/classify/predict5/*.jpg')[:10]:
  print(image_path)
  display(Image(filename=image_path, height = 416))
  print('\n')

!yolo task=classify mode=predict model={HOME}/drive/MyDrive/Data298AandB/data/train_val_test/runs/classify/train/weights/best.pt conf=0.25 source='{HOME}/drive/MyDrive/Data298AandB/data/train_val_test/test/shoes'

for image_path in glob.glob(f'{HOME}/runs/classify/predict6/*.jpg')[:10]:
  print(image_path)
  display(Image(filename=image_path, height = 416))
  print('\n')

!yolo task=classify mode=predict model={HOME}/drive/MyDrive/Data298AandB/data/train_val_test/runs/classify/train/weights/best.pt conf=0.25 source='{HOME}/drive/MyDrive/Data298AandB/data/train_val_test/test/medical'

for image_path in glob.glob(f'{HOME}/runs/classify/predict7/*.jpg')[:10]:
  print(image_path)
  display(Image(filename=image_path, height = 416))
  print('\n')

!yolo task=classify mode=predict model={HOME}/drive/MyDrive/Data298AandB/data/train_val_test/runs/classify/train/weights/best.pt conf=0.25 source='{HOME}/drive/MyDrive/Data298AandB/data/train_val_test/test/e-waste'

for image_path in glob.glob(f'{HOME}/runs/classify/predict8/*.jpg')[:10]:
  print(image_path)
  display(Image(filename=image_path, height = 416))
  print('\n')

!yolo task=classify mode=predict model={HOME}/drive/MyDrive/Data298AandB/data/train_val_test/runs/classify/train/weights/best.pt conf=0.25 source='{HOME}/drive/MyDrive/Data298AandB/data/train_val_test/test/cardboard'

for image_path in glob.glob(f'{HOME}/runs/classify/predict9/*.jpg')[:10]:
  print(image_path)
  display(Image(filename=image_path, height = 416))
  print('\n')

!yolo task=classify mode=predict model={HOME}/drive/MyDrive/Data298AandB/data/train_val_test/runs/classify/train/weights/best.pt conf=0.25 source='{HOME}/drive/MyDrive/Data298AandB/data/train_val_test/test/paper'

for image_path in glob.glob(f'{HOME}/runs/classify/predict10/*.jpg')[:10]:
  print(image_path)
  display(Image(filename=image_path, height = 416))
  print('\n')

!yolo task=classify mode=predict model={HOME}/drive/MyDrive/Data298AandB/data/train_val_test/runs/classify/train/weights/best.pt conf=0.25 source='{HOME}/drive/MyDrive/Data298AandB/data/train_val_test/test/metal'

for image_path in glob.glob(f'{HOME}/runs/classify/predict11/*.jpg')[:10]:
  print(image_path)
  display(Image(filename=image_path, height = 416))
  print('\n')

import torch
import numpy as np
from sklearn.metrics import precision_recall_fscore_support, confusion_matrix

model = YOLO('/content/drive/MyDrive/Data298AandB/YOLO_Modeling/data/yoloSmall/runs/classify/train/weights/best.pt')  # load a custom model





